# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_list_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
